# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ActionStatusEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_email', models.CharField(choices=[('buy', 'Buyer'), ('inc', 'Insurance Company'), ('psi', 'Partner - Superintendent'), ('pad', 'Partner - Administrator'), ('gop', 'GalCorr - Operational'), ('gco', 'GalCorr - Commercial'), ('gma', 'GalCorr - Manager'), ('gad', 'GalCorr - Administrator')], max_length=3)),
                ('action_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ActionStatus')),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('result_value', models.CharField(max_length=100)),
                ('domain_value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('susep', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='MethodPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Bank')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('icon1', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('icon2', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('introduction', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('declaration', models.TextField()),
                ('kind_person', models.CharField(choices=[('F', 'Individual'), ('J', 'Legal Person')], max_length=1)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Branch')),
                ('file_type', models.ManyToManyField(to='core.FileType')),
                ('insurance_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.InsuranceCompany')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('required', models.BooleanField()),
                ('type', models.CharField(choices=[('pt', 'Protection'), ('co', 'Condition'), ('pr', 'Profile'), ('pd', 'Profile Detail'), ('sl', 'Sale'), ('in', 'Information'), ('dl', 'Deadline')], max_length=2)),
                ('domain', models.ManyToManyField(to='product.Domain')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='question',
            field=models.ManyToManyField(to='product.Question'),
        ),
        migrations.AddField(
            model_name='methodpayment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='actionstatus',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='actionstatus',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Status'),
        ),
    ]
