# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('susep', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email address')),
            ],
        ),
        migrations.CreateModel(
            name='MethodPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Name')),
                ('disclaimer', models.CharField(max_length=100, null=True, verbose_name='Disclaimer')),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Bank')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('image', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Image')),
                ('icon1', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Icon 1')),
                ('icon2', models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Icon 2')),
                ('introduction', models.CharField(max_length=50, verbose_name='Introduction')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('declaration', models.TextField(blank=True, null=True, verbose_name='Declaration')),
                ('full_declaration', models.TextField(blank=True, null=True, verbose_name='Full Declaration')),
                ('kind_person', models.CharField(choices=[('F', 'Individual'), ('J', 'Legal Person')], max_length=1)),
                ('is_lead', models.BooleanField(default=False)),
                ('partner_percentage', models.FloatField(blank=True, default=0, null=True)),
                ('owner_percentage', models.FloatField(blank=True, default=0, null=True)),
                ('master_percentage', models.FloatField(blank=True, default=0, null=True)),
                ('director_percentage', models.FloatField(blank=True, default=0, null=True)),
                ('other_documents_declaration', models.CharField(max_length=100, null=True, verbose_name='Other Documentos')),
                ('rules_declaration', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rules')),
                ('disclaimer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rules')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('hint', models.CharField(blank=True, max_length=100, verbose_name='Hint')),
                ('type_group', models.CharField(choices=[('hea', 'Header'), ('bro', 'Broker'), ('cli', 'Client'), ('ins', 'Insured'), ('com', 'Commercial Protection'), ('pro', 'Profile Protection'), ('ten', 'Tenant'), ('pss', 'Process'), ('leg', 'Legal Opinion'), ('oth', 'Other information'), ('col', 'Collection'), ('cdn', 'Condition'), ('foo', 'Footer')], max_length=3)),
                ('type_profile', models.CharField(choices=[('pdl', 'Profile Deadline'), ('pdt', 'Profile Detail')], max_length=3)),
                ('type_data', models.CharField(choices=[('input', 'Input'), ('checkbox', 'CheckBox'), ('float', 'Float'), ('link', 'Link'), ('select', 'Select'), ('date', 'Date'), ('text', 'Text'), ('percent', 'Percent'), ('number', 'Number')], max_length=10)),
                ('rule', models.CharField(blank=True, max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_printable', models.BooleanField(default=False)),
                ('is_required', models.BooleanField(default=False)),
                ('is_comment', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=100)),
                ('order_number', models.IntegerField(blank=True, null=True)),
                ('col_width', models.IntegerField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='RuleProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percent', models.FloatField(blank=True, default=0, null=True)),
                ('rate', models.FloatField(blank=True, default=0, null=True)),
                ('fixing_text', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, choices=[('F', 'Fixing'), ('V', 'Variable')], max_length=1, null=True)),
                ('value', models.FloatField(blank=True, default=0, null=True)),
                ('rule', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'Rules',
            },
        ),
        migrations.CreateModel(
            name='SampleFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('document', models.FileField(upload_to=b'')),
                ('file_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.FileType')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='begin_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Status'),
        ),
        migrations.AddField(
            model_name='product',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Branch'),
        ),
        migrations.AddField(
            model_name='product',
            name='file_type',
            field=models.ManyToManyField(to='product.FileType'),
        ),
        migrations.AddField(
            model_name='product',
            name='insurance_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.InsuranceCompany'),
        ),
        migrations.AddField(
            model_name='product',
            name='method_payment',
            field=models.ManyToManyField(to='product.MethodPayment'),
        ),
        migrations.AddField(
            model_name='product',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Profile'),
        ),
        migrations.AddField(
            model_name='product',
            name='rules',
            field=models.ManyToManyField(blank=True, to='product.RuleProduct'),
        ),
        migrations.AddField(
            model_name='product',
            name='sample_file_type',
            field=models.ManyToManyField(blank=True, to='product.SampleFile'),
        ),
        migrations.AddField(
            model_name='product',
            name='status_permission',
            field=models.ManyToManyField(related_name='product_status_permission', to='product.Status'),
        ),
        migrations.AddField(
            model_name='domain',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Question'),
        ),
        migrations.AddField(
            model_name='actionstatus',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='actionstatus',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Status'),
        ),
    ]
