# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sample_file_type',
            field=models.ManyToManyField(blank=True, to='product.SampleFile'),
        ),
    ]
