# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rules_js',
            field=models.TextField(blank=True, null=True, verbose_name='Rule JS'),
        ),
    ]
