# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_lead',
            field=models.BooleanField(default=False),
        ),
    ]
