# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='print_col_width',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type_data',
            field=models.CharField(choices=[('input', 'Input'), ('checkbox', 'CheckBox'), ('float', 'Float'), ('link', 'Link'), ('select', 'Select'), ('date', 'Date'), ('text', 'Text'), ('percent', 'Percent'), ('number', 'Number')], max_length=10),
        ),
    ]
