# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 04:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20160510_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='domain_value',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='result_value',
        ),
    ]
