# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_rules_js'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecompany',
            name='icon',
            field=models.ImageField(blank=True, upload_to='uploads/%Y/%m/%d/', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='product',
            name='other_documents_declaration',
            field=models.CharField(default=True, max_length=100, null=True, verbose_name='Other Documentos'),
        ),
    ]
