# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 01:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20160511_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='create_timestamp',
            field=models.DateField(default=datetime.datetime(2016, 5, 11, 1, 31, 23, 462008, tzinfo=utc), verbose_name='Date Created'),
        ),
    ]
