# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassificadoGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='First name')),
                ('menu_products', models.BooleanField(default=False, verbose_name='Products')),
                ('menu_dashboard', models.BooleanField(default=False, verbose_name='Dashboard')),
                ('menu_production', models.BooleanField(default=False, verbose_name='Production')),
                ('menu_entries', models.BooleanField(default=False, verbose_name='Entries')),
                ('menu_entries_users', models.BooleanField(default=False, verbose_name='Users')),
                ('menu_entries_profiles', models.BooleanField(default=False, verbose_name='Profiles')),
                ('menu_entries_partners', models.BooleanField(default=False, verbose_name='Partners')),
                ('menu_entries_products', models.BooleanField(default=False, verbose_name='Products')),
                ('menu_notification', models.BooleanField(default=False, verbose_name='Notification')),
                ('menu_profile', models.BooleanField(default=False, verbose_name='Profile')),
                ('filetype_download', models.ManyToManyField(to='product.FileTypeDownload')),
                ('filetype_see', models.ManyToManyField(to='product.FileTypeSee')),
                ('product', models.ManyToManyField(to='product.Product')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.AddField(
            model_name='massificadogroups',
            name='profiles',
            field=models.ManyToManyField(to='user_groups.Profiles'),
        ),
        migrations.AddField(
            model_name='massificadogroups',
            name='status_edit',
            field=models.ManyToManyField(to='product.StatusEdit'),
        ),
        migrations.AddField(
            model_name='massificadogroups',
            name='status_see',
            field=models.ManyToManyField(to='product.StatusSee'),
        ),
        migrations.AddField(
            model_name='massificadogroups',
            name='status_set',
            field=models.ManyToManyField(to='product.StatusSet'),
        ),
    ]
