# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassificadoGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('menu_products', models.BooleanField(default=False, verbose_name='Products')),
                ('menu_dashboard', models.BooleanField(default=False, verbose_name='Dashboard')),
                ('menu_production', models.BooleanField(default=False, verbose_name='Production')),
                ('menu_entries', models.BooleanField(default=False, verbose_name='Entries')),
                ('menu_entries_users', models.BooleanField(default=False, verbose_name='Users')),
                ('menu_entries_profiles', models.BooleanField(default=False, verbose_name='Profiles')),
                ('menu_entries_partners', models.BooleanField(default=False, verbose_name='Partners')),
                ('menu_entries_products', models.BooleanField(default=False, verbose_name='Products')),
                ('menu_notification', models.BooleanField(default=False, verbose_name='Notification')),
                ('menu_profile', models.BooleanField(default=False, verbose_name='Profile')),
                ('filetype_download', models.ManyToManyField(blank=True, related_name='user_filetype_download', to='product.FileType')),
                ('filetype_see', models.ManyToManyField(blank=True, related_name='user_filetype_see', to='product.FileType')),
                ('product', models.ManyToManyField(blank=True, to='product.Product')),
                ('profiles', models.ManyToManyField(blank=True, related_name='_massificadogroups_profiles_+', to='user_groups.MassificadoGroups')),
                ('status_edit', models.ManyToManyField(blank=True, related_name='user_status_edit', to='product.Status')),
                ('status_see', models.ManyToManyField(blank=True, related_name='user_status_see', to='product.Status')),
                ('status_set', models.ManyToManyField(blank=True, related_name='user_status_set', to='product.Status')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'Permissions',
            },
        ),
    ]
