# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('user_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='massificadogroups',
            name='status_edit_data',
            field=models.ManyToManyField(blank=True, related_name='user_status_edit_data', to='product.Status'),
        ),
        migrations.AddField(
            model_name='massificadogroups',
            name='status_edit_deadline',
            field=models.ManyToManyField(blank=True, related_name='user_status_edit_deadline', to='product.Status'),
        ),
        migrations.AddField(
            model_name='massificadogroups',
            name='status_edit_payment',
            field=models.ManyToManyField(blank=True, related_name='user_status_edit_payment', to='product.Status'),
        ),
        migrations.AddField(
            model_name='massificadogroups',
            name='status_see_data',
            field=models.ManyToManyField(blank=True, related_name='user_status_see_data', to='product.Status'),
        ),
        migrations.AddField(
            model_name='massificadogroups',
            name='status_see_deadline',
            field=models.ManyToManyField(blank=True, related_name='user_status_see_deadline', to='product.Status'),
        ),
        migrations.AddField(
            model_name='massificadogroups',
            name='status_see_payment',
            field=models.ManyToManyField(blank=True, related_name='user_status_see_payment', to='product.Status'),
        ),
    ]
