# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0002_auto_20160606_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massificadogroups',
            name='status_edit_data',
        ),
        migrations.RemoveField(
            model_name='massificadogroups',
            name='status_see_data',
        ),
    ]
