# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_groups', '0003_auto_20160606_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='massificadogroups',
            name='quote_see',
            field=models.BooleanField(default=False, verbose_name='See Quote'),
        ),
    ]
