# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 02:58
from __future__ import unicode_literals

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('auth', '0007_alter_validators_add_error_messages'),
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassificadoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(help_text='Required. 30 characters or fewer. Letters, numbers and ./+/-/_ characters', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.+-]+$'), 'Enter a valid username.', 'invalid')], verbose_name='Username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Last name')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date joined')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'permissions': (),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MassificadoGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='First name')),
                ('menu_products', models.BooleanField(default=False, verbose_name='Products')),
                ('menu_dashboard', models.BooleanField(default=False, verbose_name='Dashboard')),
                ('menu_production', models.BooleanField(default=False, verbose_name='Production')),
                ('menu_entries', models.BooleanField(default=False, verbose_name='Entries')),
                ('menu_entries_users', models.BooleanField(default=False, verbose_name='Users')),
                ('menu_entries_profiles', models.BooleanField(default=False, verbose_name='Profiles')),
                ('menu_entries_partners', models.BooleanField(default=False, verbose_name='Partners')),
                ('menu_entries_products', models.BooleanField(default=False, verbose_name='Products')),
                ('menu_notification', models.BooleanField(default=False, verbose_name='Notification')),
                ('menu_profile', models.BooleanField(default=False, verbose_name='Profile')),
                ('filetype_download', models.ManyToManyField(to='product.FileTypeDownload')),
                ('filetype_see', models.ManyToManyField(to='product.FileTypeSee')),
                ('product', models.ManyToManyField(to='product.Product')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.AddField(
            model_name='massificadogroups',
            name='profiles',
            field=models.ManyToManyField(to='user_account.Profiles'),
        ),
        migrations.AddField(
            model_name='massificadogroups',
            name='status_edit',
            field=models.ManyToManyField(to='product.StatusEdit'),
        ),
        migrations.AddField(
            model_name='massificadogroups',
            name='status_see',
            field=models.ManyToManyField(to='product.StatusSee'),
        ),
        migrations.AddField(
            model_name='massificadogroups',
            name='status_set',
            field=models.ManyToManyField(to='product.StatusSet'),
        ),
        migrations.AddField(
            model_name='massificadouser',
            name='group_permissions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_account.MassificadoGroups'),
        ),
        migrations.AddField(
            model_name='massificadouser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='massificadouser',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.Partner'),
        ),
        migrations.AddField(
            model_name='massificadouser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
