# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionStatusEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_email', models.CharField(choices=[('buy', 'Buyer'), ('inc', 'Insurance Company'), ('own', 'Owner'), ('usr', 'Users')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ActionStatusEmailsUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_status_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status_emails.ActionStatusEmails')),
            ],
        ),
    ]
