# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 06:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('status_emails', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actionstatusemailsusers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actionstatusemails',
            name='action_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ActionStatus'),
        ),
    ]
