# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 23:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sale', '0001_initial'),
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subquote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Buyer'),
        ),
        migrations.AddField(
            model_name='sale',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.Partner'),
        ),
        migrations.AddField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='responsedetail',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Detail'),
        ),
        migrations.AddField(
            model_name='responsedetail',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Question'),
        ),
        migrations.AddField(
            model_name='responsedeadline',
            name='deadline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Deadline'),
        ),
        migrations.AddField(
            model_name='responsedeadline',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Question'),
        ),
        migrations.AddField(
            model_name='quote',
            name='deadline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Deadline'),
        ),
        migrations.AddField(
            model_name='file',
            name='deadline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Deadline'),
        ),
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.FileType'),
        ),
        migrations.AddField(
            model_name='file',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detail',
            name='deadline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Deadline'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='lives',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Vidas', to='sale.NumberLives', verbose_name='Lives'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='method_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='method', to='product.MethodPayment', verbose_name='Method'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='rules',
            field=models.ManyToManyField(blank=True, to='sale.RuleDeadLine'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Sale'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Status'),
        ),
        migrations.AddField(
            model_name='buyeraddress',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Buyer'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='activity_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.ActivityArea', verbose_name='Activity'),
        ),
    ]
