# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 07:36
from __future__ import unicode_literals

import address.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0001_initial'),
        ('product', '0001_initial'),
        ('address', '0001_initial'),
        ('sale', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subquote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Buyer'),
        ),
        migrations.AddField(
            model_name='sale',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.Partner'),
        ),
        migrations.AddField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Status'),
        ),
        migrations.AddField(
            model_name='response',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Detail'),
        ),
        migrations.AddField(
            model_name='response',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Question'),
        ),
        migrations.AddField(
            model_name='quote',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Sale'),
        ),
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FileType'),
        ),
        migrations.AddField(
            model_name='file',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Sale'),
        ),
        migrations.AddField(
            model_name='detail',
            name='deadline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Deadline'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Sale'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Address'),
        ),
        migrations.AddField(
            model_name='address',
            name='address',
            field=address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.Address'),
        ),
    ]
