# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 01:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20160510_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='create_timestamp',
            field=models.DateField(default=datetime.datetime(2016, 5, 10, 1, 51, 38, 703923, tzinfo=utc), verbose_name='Date Created'),
        ),
    ]
