# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20160530_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberLives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True, verbose_name='Number')),
            ],
        ),
        migrations.AddField(
            model_name='deadline',
            name='costing',
            field=models.CharField(choices=[('N', 'Not Contributory')], default='N', max_length=1, null=True, verbose_name='Costing'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='insured_capital',
            field=models.FloatField(null=True, verbose_name='Insured Capital'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='insured_group',
            field=models.CharField(choices=[('O', 'Officials and Partners/Directors')], default='O', max_length=1, null=True, verbose_name='Insured Group'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='rate_per_thousand',
            field=models.FloatField(null=True, verbose_name='Rate per Thousand'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='revenues',
            field=models.CharField(choices=[('Y', 'Yearly')], default='Y', max_length=1, null=True, verbose_name='Revenues'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='lives',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.NumberLives'),
        ),
    ]
