# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20160501_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='modificate_timestamp',
        ),
    ]
