# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_remove_sale_modificate_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='email',
        ),
    ]
