# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 02:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_auto_20160510_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='create_timestamp',
            field=models.DateField(default=datetime.datetime(2016, 5, 10, 2, 44, 46, 666117, tzinfo=utc), verbose_name='Date Created'),
        ),
    ]
