# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_auto_20160606_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deadline',
            name='rules',
        ),
        migrations.AddField(
            model_name='ruledeadline',
            name='deadline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sale.Deadline'),
            preserve_default=False,
        ),
    ]
