# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 04:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_auto_20160510_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='create_timestamp',
            field=models.DateField(default=datetime.datetime(2016, 5, 10, 4, 31, 20, 156018, tzinfo=utc), verbose_name='Date Created'),
        ),
    ]
