# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('sale', '0004_remove_sale_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='modificate',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='address',
        ),
        migrations.AddField(
            model_name='buyer',
            name='address',
            field=models.ManyToManyField(to='address.Address'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
