# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 06:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20160510_0431'),
        ('sale', '0005_auto_20160510_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Detail')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='responsedatail',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='responsedatail',
            name='question',
        ),
        migrations.AddField(
            model_name='responsedeadline',
            name='value',
            field=models.TextField(default='x'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='create_timestamp',
            field=models.DateField(default=datetime.datetime(2016, 5, 10, 6, 1, 11, 24344, tzinfo=utc), verbose_name='Date Created'),
        ),
        migrations.DeleteModel(
            name='ResponseDatail',
        ),
    ]
