# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_auto_20160502_0448'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100, verbose_name='Street')),
                ('district', models.CharField(max_length=20, verbose_name='District')),
                ('complement', models.CharField(max_length=20, verbose_name='Complement')),
                ('number', models.CharField(max_length=6, verbose_name='Number')),
                ('city', models.CharField(max_length=20, verbose_name='City')),
                ('state', models.CharField(max_length=20, verbose_name='State')),
                ('postal_code', models.CharField(max_length=9, verbose_name='Postal Code')),
                ('is_main', models.BooleanField(verbose_name='Main Address')),
            ],
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='address',
        ),
        migrations.AddField(
            model_name='buyeraddress',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Buyer'),
        ),
    ]
