# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 16:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_auto_20160510_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='name',
            field=models.CharField(default='Name\x7f"\x7f', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='create_timestamp',
            field=models.DateField(default=datetime.datetime(2016, 5, 10, 16, 27, 45, 187676, tzinfo=utc), verbose_name='Date Created'),
        ),
    ]
