# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='modificate',
        ),
        migrations.AddField(
            model_name='partner',
            name='site',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.FileField(null=True, upload_to=b''),
        ),
    ]
