# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_auto_20160501_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
