# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_auto_20160501_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='slug',
        ),
        migrations.AlterField(
            model_name='partner',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
